<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OptionInfer>On</OptionInfer>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="DevExpress.RichEdit.Export" Version="24.2.*-*" />
    <PackageReference Include="DevExpress.Win.Map" Version="24.2.*-*" />
    <PackageReference Include="DevExpress.Win.RichEdit" Version="24.2.*-*" />
    <PackageReference Include="System.Text.Json">
      <Version>8.0.5</Version>
    </PackageReference>
  </ItemGroup>
</Project>